# Gradle
kotlin.code.style=official
kotlin.incremental=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.tooling.parallel=true
# Java
klibs.java.source=21
klibs.java.target=25
klibs.java.ktarget=25
# Project
klibs.project.name=AstraLibs
klibs.project.group=ru.astrainteractive.astralibs
klibs.project.version.string=3.43.0
klibs.project.description=Core utilities for spigot development
klibs.project.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com
klibs.project.url=https://empireprojekt.ru
# Publish
klibs.publish.name=AstraLibs
klibs.publish.groupId=ru.astrainteractive.astralibs
klibs.publish.description=Core utilities for spigot development
klibs.publish.repo.org=Astra-Interactive
klibs.publish.repo.name=AstraLibs
klibs.publish.license=Custom
klibs.publish.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com
